image: php:7.1.3

# Select what we should cache between builds
cache:
  paths:
  - vendor/

before_script:
- apt-get update -yqq
- apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
# Install PHP extensions
- docker-php-ext-install bcmath intl mcrypt mbstring mysqli opcache soap xsl zip bz2 exif
- docker-php-ext-configure gd --enable-gd-native-ttf --with-jpeg-dir=/usr/lib/x86_64-linux-gnu/ --with-png-dir=/usr/lib/x86_64-linux-gnu/ --with-freetype-dir=/usr/lib/x86_64-linux-gnu/
- docker-php-ext-install gd

# Install and run Composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar config --global http-basic.repo.magento.com "$MAGENTO_USERNAME" "$MAGENTO_PASSWORD"
- php composer.phar install

stages:
- build
- deploy

build:
  stage: build
  script: ./vendor/bin/dep build
  artifacts:
    paths:
      - artifacts/artifact.tar.gz
    expire_in: 30 days

deploy_stage:
  stage: deploy
  script: ./vendor/bin/dep deploy-artifact release
  only:
    - feature/gitlab-config